
# This file controls the configuration for your Supabase project.
# For the full list of options available, visit the project settings page.

project_id = "uwgclposhhdovfjnazlp"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322

[studio]
port = 54323

[functions.send-email]
verify_jwt = true

[auth]
# Redirect URLs from Authentication
redirect_urls = ["http://*.supabase.co/*", "http://localhost:3000/*", "https://*.webflow.io/*", "https://*.lovable.app/*"]
site_url = "https://uwgclposhhdovfjnazlp.lovable.app"
